### ISSUE TITLE
Problem with generated URLs (#accordion...)

### ISSUE THREAD

**Issue by micha68g** [Hauer-Heinrich/hh_accordion#5]
hh_accordion 0.3.5 and 0.4.1

After click on one of the accordion- or tab-elements  the url changes to:
"www.domain.de/#accordion-188-2" (e.g.)
 
 instead of "www.domain.de/subpath-1/subpath-2#accordion-188-2"

I would expect, that the accordion/tab urls would always look like:
www.domain.de/subpath-1/subpath-2/#accordion-188-2

TYPO3 - Version 11.5.x

Maybe I missed some configuration?

Thanks
Michael

**Comment by Teisi** [comment]
why should it change to "www.domain.de/subpath-1/subpath-2"? Sorry i don't get the question? Accordions aren't sites.

**Comment by micha68g** [comment]
well, my explanation was perhaps not so optimal...

if I put an accordion-element on this page:
www.domain.de/subpath-1/subpath-2 

I would expect, that, if I open the accordion on this page, the address line of the browser changes to:
www.domain.de/subpath-1/subpath-2#accordion-188-2

but I get:
www.domain.de/#accordion-188-2

so, when I reload the page for example, I'm on the rootpage, not on www.domain.de/subpath-1/subpath-2 anymore

greetings
Michael

**Comment by Teisi** [comment]
@micha68g  Can you share your siteconfig yaml please?

**Comment by micha68g** [comment]
sure...some anonymisation

```
base: 'https://www.domainname.de/'
disableStaticFileCache: false
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: global
    websiteTitle: 'Websitetitle here...changed'
rootPageId: 1
websiteTitle: 'Websitetitle here...changed'
```
